version: '3.9'
services:
    nginx:
        container_name: hintonmovieonepage
        image: nginx:1.23.3
        ports:
            - 8080:80
        volumes:
            - ./build:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
